/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInfo = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : Address,
  'phone' : IDL.Text,
});
export const Time = IDL.Int;
export const Client = IDL.Record({
  'blacklistMedia' : IDL.Vec(ExternalBlob),
  'blacklistComments' : IDL.Text,
  'info' : ContactInfo,
  'updatedAt' : Time,
  'isBlacklisted' : IDL.Bool,
});
export const Intervention = IDL.Record({
  'id' : IDL.Text,
  'media' : IDL.Vec(ExternalBlob),
  'clientId' : IDL.Text,
  'date' : IDL.Record({ 'day' : IDL.Nat, 'month' : IDL.Nat, 'year' : IDL.Nat }),
  'updatedAt' : Time,
  'employee' : IDL.Principal,
  'comments' : IDL.Text,
  'interventionTimestamp' : Time,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addIntervention' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateClient' : IDL.Func(
      [IDL.Text, IDL.Text, Address, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteIntervention' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Text], [Client], ['query']),
  'getClientInterventions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Intervention)],
      ['query'],
    ),
  'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsBlacklisted' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchClients' : IDL.Func([IDL.Text], [IDL.Vec(Client)], ['query']),
  'unmarkAsBlacklisted' : IDL.Func([IDL.Text], [], []),
  'updateIntervention' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(ExternalBlob),
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInfo = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : Address,
    'phone' : IDL.Text,
  });
  const Time = IDL.Int;
  const Client = IDL.Record({
    'blacklistMedia' : IDL.Vec(ExternalBlob),
    'blacklistComments' : IDL.Text,
    'info' : ContactInfo,
    'updatedAt' : Time,
    'isBlacklisted' : IDL.Bool,
  });
  const Intervention = IDL.Record({
    'id' : IDL.Text,
    'media' : IDL.Vec(ExternalBlob),
    'clientId' : IDL.Text,
    'date' : IDL.Record({
      'day' : IDL.Nat,
      'month' : IDL.Nat,
      'year' : IDL.Nat,
    }),
    'updatedAt' : Time,
    'employee' : IDL.Principal,
    'comments' : IDL.Text,
    'interventionTimestamp' : Time,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addIntervention' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateClient' : IDL.Func(
        [IDL.Text, IDL.Text, Address, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteIntervention' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Text], [Client], ['query']),
    'getClientInterventions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Intervention)],
        ['query'],
      ),
    'getClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsBlacklisted' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Vec(ExternalBlob)],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchClients' : IDL.Func([IDL.Text], [IDL.Vec(Client)], ['query']),
    'unmarkAsBlacklisted' : IDL.Func([IDL.Text], [], []),
    'updateIntervention' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };