/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'city' : string,
  'state' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Client {
  'blacklistMedia' : Array<ExternalBlob>,
  'blacklistComments' : string,
  'info' : ContactInfo,
  'updatedAt' : Time,
  'isBlacklisted' : boolean,
}
export interface ContactInfo {
  'name' : string,
  'email' : string,
  'address' : Address,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Intervention {
  'id' : string,
  'media' : Array<ExternalBlob>,
  'clientId' : string,
  'date' : { 'day' : bigint, 'month' : bigint, 'year' : bigint },
  'canEdit' : boolean,
  'updatedAt' : Time,
  'employee' : Principal,
  'canDelete' : boolean,
  'comments' : string,
  'interventionTimestamp' : Time,
}
export interface MediaItem {
  'id' : string,
  'owner' : Principal,
  'file' : ExternalBlob,
  'createdAt' : Time,
}
export interface ScheduledIntervention {
  'id' : string,
  'media' : Array<ExternalBlob>,
  'startTime' : string,
  'clientId' : string,
  'endTime' : string,
  'clientName' : string,
  'weekYear' : bigint,
  'date' : { 'day' : bigint, 'month' : bigint, 'year' : bigint },
  'createdAt' : Time,
  'createdBy' : Principal,
  'description' : string,
  'weekNumber' : bigint,
  'updatedAt' : Time,
  'clientSignature' : [] | [string],
  'employeeSignature' : [] | [string],
  'assignedEmployee' : Principal,
  'reason' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkHours {
  'id' : string,
  'date' : { 'day' : bigint, 'month' : bigint, 'year' : bigint },
  'morningEnd' : string,
  'afternoonStart' : string,
  'updatedAt' : Time,
  'employee' : Principal,
  'afternoonEnd' : string,
  'morningStart' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface BillingPart {
  'reference' : string,
  'quantity' : string,
}
export interface BillingRecord {
  'id' : string,
  'interventionId' : string,
  'clientId' : string,
  'clientName' : string,
  'employeeName' : string,
  'reason' : string,
  'date' : { 'day' : bigint, 'month' : bigint, 'year' : bigint },
  'parts' : Array<BillingPart>,
  'comment' : string,
  'status' : string,
  'createdAt' : bigint,
}
export interface Memo {
  'id' : string,
  'authorPrincipal' : Principal,
  'authorName' : string,
  'title' : string,
  'content' : string,
  'media' : Array<ExternalBlob>,
  'voiceNote' : [] | [ExternalBlob],
  'createdAt' : Time,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addIntervention' : ActorMethod<
    [string, string, Array<ExternalBlob>, bigint, bigint, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimAdminIfNoneExists' : ActorMethod<[], undefined>,
  'createFolder' : ActorMethod<[string], undefined>,
  'createOrUpdateClient' : ActorMethod<
    [string, string, Address, string, string],
    undefined
  >,
  'createScheduledIntervention' : ActorMethod<
    [
      string,
      string,
      Principal,
      string,
      string,
      string,
      string,
      Array<ExternalBlob>,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
    ],
    string
  >,
  'deleteIntervention' : ActorMethod<[string, string], undefined>,
  'deleteMediaItem' : ActorMethod<[string], undefined>,
  'deleteScheduledIntervention' : ActorMethod<[string], undefined>,
  'deleteTechnicalFileWithPath' : ActorMethod<[string], undefined>,
  'downloadTechnicalFileWithPath' : ActorMethod<[string], [] | [ExternalBlob]>,
  'getAllEmployeesWorkHoursForMonth' : ActorMethod<
    [bigint, bigint],
    Array<WorkHours>
  >,
  'getApprovedEmployees' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[string], Client>,
  'getClientInterventions' : ActorMethod<[string], Array<Intervention>>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getClientsWithIds' : ActorMethod<[], Array<[string, Client]>>,
  'getInterventionsByDate' : ActorMethod<
    [bigint, bigint, bigint],
    Array<Intervention>
  >,
  'getMediaItem' : ActorMethod<[string], [] | [MediaItem]>,
  'getScheduledInterventionById' : ActorMethod<
    [string],
    [] | [ScheduledIntervention]
  >,
  'getScheduledInterventionsByWeek' : ActorMethod<
    [bigint, bigint],
    Array<ScheduledIntervention>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProfilesByPrincipals' : ActorMethod<
    [Array<Principal>],
    Array<[Principal, UserProfile]>
  >,
  'getWorkHoursForMonth' : ActorMethod<
    [Principal, bigint, bigint],
    Array<WorkHours>
  >,
  'hasAdminRegistered' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listAllMediaItems' : ActorMethod<[], Array<MediaItem>>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listTechnicalFiles' : ActorMethod<[], Array<[string, ExternalBlob]>>,
  'markAsBlacklisted' : ActorMethod<
    [string, string, Array<ExternalBlob>],
    undefined
  >,
  'moveTechnicalFile' : ActorMethod<[string, string], undefined>,
  'renameFolder' : ActorMethod<[string, string], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveWorkHours' : ActorMethod<
    [bigint, bigint, bigint, string, string, string, string],
    undefined
  >,
  'searchClients' : ActorMethod<[string], Array<Client>>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'syncAdminRole' : ActorMethod<[], boolean>,
  'unmarkAsBlacklisted' : ActorMethod<[string], undefined>,
  'updateIntervention' : ActorMethod<
    [string, string, string, Array<ExternalBlob>, bigint, bigint, bigint],
    undefined
  >,
  'updateScheduledIntervention' : ActorMethod<
    [
      string,
      string,
      string,
      Principal,
      string,
      string,
      string,
      string,
      Array<ExternalBlob>,
      [] | [string],
      [] | [string],
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
    ],
    undefined
  >,
  'createBillingRecord' : ActorMethod<
    [string, string, string, string, string, bigint, bigint, bigint, Array<BillingPart>, string],
    string
  >,
  'getBillingRecords' : ActorMethod<[], Array<BillingRecord>>,
  'updateBillingRecordStatus' : ActorMethod<[string, string], undefined>,
  'deleteBillingRecord' : ActorMethod<[string], undefined>,
  'uploadMediaItem' : ActorMethod<[{ 'file' : ExternalBlob }], string>,
  'uploadTechnicalFileWithFolderPath' : ActorMethod<
    [string, ExternalBlob],
    undefined
  >,
  'getAllUserProfiles' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getMemos' : ActorMethod<[], Array<Memo>>,
  'createMemo' : ActorMethod<[string, string, string, Array<ExternalBlob>, [] | [ExternalBlob]], string>,
  'deleteMemo' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];