/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'city' : string,
  'state' : string,
}
export interface Client {
  'blacklistMedia' : Array<ExternalBlob>,
  'blacklistComments' : string,
  'info' : ContactInfo,
  'updatedAt' : Time,
  'isBlacklisted' : boolean,
}
export interface ContactInfo {
  'name' : string,
  'email' : string,
  'address' : Address,
  'phone' : string,
}
export type ExternalBlob = Uint8Array;
export interface Intervention {
  'id' : string,
  'media' : Array<ExternalBlob>,
  'clientId' : string,
  'date' : { 'day' : bigint, 'month' : bigint, 'year' : bigint },
  'updatedAt' : Time,
  'employee' : Principal,
  'comments' : string,
  'interventionTimestamp' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addIntervention' : ActorMethod<
    [string, string, Array<ExternalBlob>, bigint, bigint, bigint],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateClient' : ActorMethod<
    [string, string, Address, string, string],
    undefined
  >,
  'deleteIntervention' : ActorMethod<[string, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[string], Client>,
  'getClientInterventions' : ActorMethod<[string], Array<Intervention>>,
  'getClients' : ActorMethod<[], Array<Client>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsBlacklisted' : ActorMethod<
    [string, string, Array<ExternalBlob>],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchClients' : ActorMethod<[string], Array<Client>>,
  'unmarkAsBlacklisted' : ActorMethod<[string], undefined>,
  'updateIntervention' : ActorMethod<
    [string, string, string, Array<ExternalBlob>, bigint, bigint, bigint],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];